(DEFINE (AVERGE X Y)
	(/ (+ X Y) 2))

(DEFINE (FIXED-POINT F START)
	(DEFINE TOLERANCE 0.00001)
	(DEFINE (CLOSE-ENUF? U V)
		(< (abs (- u v)) TOLENRANCE))
	(DEFINE (ITER OLD NEW)
		(IF (CLOSE-ENUF? OLD NEW))
		NEW
		(ITER NEW (F NEW)))
	(ITER START (F START)))

;(DEFINE (SQRT X)
;	(FIXED-POINT (LAMBDA(Y)(AVERGE (/ X Y) Y))
;		       1))

(DEFINE AVERAGE-DAMP 
	(LAMBDA(F)
	  (LAMBDA(X)(AVERAGE (F X) X))))

(DEFINE (SQRT X)
	(FIXED-POINT (AVERAGE-DAMP(LAMBDA(Y)(/ X Y)))
		     1))

SQRT 4
